import type { Service } from './types/ServiceType';

export const services: Service[] = [
  {
    id: 1,
    title: 'service.oneTimeInspection.title',
    price: '299zł',
    icon: 'icon--one-time-diagnostics',
    description: 'service.oneTimeInspection.description',
    bargain: 'service.oneTimeInspection.bargain',
    includedServices: [
      'service.oneTimeInspection.service1',
      'service.oneTimeInspection.service2',
      'service.oneTimeInspection.service3',
      'service.oneTimeInspection.service4',
      'service.oneTimeInspection.service5',
      'service.oneTimeInspection.service6',
      'service.oneTimeInspection.service7',
      'service.oneTimeInspection.service8',
      'service.oneTimeInspection.service9',
      'service.oneTimeInspection.service10',
      'service.oneTimeInspection.service11',
    ],
  },
  {
    id: 2,
    recomended: true,
    title: 'service.keyAutoSelection.title',
    price: '1200 zł',
    icon: 'icon--key',
    description: 'service.keyAutoSelection.description',
    bargain: 'service.keyAutoSelection.bargain',
    includedServices: [
      'service.keyAutoSelection.service1',
      'service.keyAutoSelection.service2',
      'service.keyAutoSelection.service3',
      'service.keyAutoSelection.service4',
      'service.keyAutoSelection.service5',
      'service.keyAutoSelection.service6',
      'service.keyAutoSelection.service7',
      'service.keyAutoSelection.service8',
      'service.keyAutoSelection.service9',
    ],
  },
  {
    id: 4,
    title: 'service.premiumAutoSelection.title',
    bargain: ' ',
    price: '2490 zł',
    icon: 'icon--prem',
    description: 'service.premiumAutoSelection.description',
    includedServices: [
      'service.premiumAutoSelection.service1',
      'service.premiumAutoSelection.service2',
      'service.premiumAutoSelection.service3',
      'service.premiumAutoSelection.service4',
      'service.premiumAutoSelection.service5',
      'service.premiumAutoSelection.service6',
    ],
  },
  {
    id: 5,
    title: 'service.expertOnDay.title',
    icon: 'icon--calendar',
    price: '750 zł',
    description: 'service.expertOnDay.description',
    includedServices: [
      'service.expertOnDay.service1',
      'service.expertOnDay.service2',
      'service.expertOnDay.service3',
      'service.expertOnDay.service4',
      'service.expertOnDay.service5',
      'service.expertOnDay.service6',
      'service.expertOnDay.service7',
      'service.expertOnDay.service8',
      'service.expertOnDay.service9',
    ],
    suitableFor: 'service.expertOnDay.suitableFor',
  },
];
